apiVersion: v1
kind: Service
metadata:
  name: backend-jonas-zubieta-service
  namespace: jonas-zubieta-namespace
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-jonas-zubieta-deployment