
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-jonas-zubieta-deployment
  namespace: jonas-zubieta-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-jonas-zubieta-deployment
  template:
    metadata:
      labels:
        app: backend-jonas-zubieta-deployment
    spec:
      containers:
      - name: backend-jonas-zubieta-deployment
        image: jonaszl/casa_nph_peru:lastest
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: jonas-zubieta-configmap
              key: DATABASE_URL
        - name: DATABASE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: jonas-zubieta-configmap
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: jonas-zubieta-configmap
              key: DATABASE_PASSWORD
        resources:
          requests:
            memory: "200Mi" 
            cpu: "1"       
          limits:
            memory: "200Mi"
            cpu: "1"  