apiVersion: v1
kind: Service
metadata:
  name:  frontend-jonas-zubieta-service
  namespace: jonas-zubieta-namespace
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
  selector:
    app:  frontend-jonas-zubieta-deployment